"""Возврат к начальным моделям

Revision ID: e4d1d8f080ac
Revises: e9deb1e563b7
Create Date: 2024-03-05 18:55:44.107652

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4d1d8f080ac'
down_revision: Union[str, None] = 'e9deb1e563b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
