"""Исправление repr базовой модели

Revision ID: 217cedc3f48f
Revises: fa81a4099709
Create Date: 2024-03-07 09:54:28.289263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217cedc3f48f'
down_revision: Union[str, None] = 'fa81a4099709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
