"""Добавление даты закрытия в repr базовой модели

Revision ID: 946e688f2e3f
Revises: 217cedc3f48f
Create Date: 2024-03-08 11:26:58.605169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946e688f2e3f'
down_revision: Union[str, None] = '217cedc3f48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
