"""Правка абстрактной модели, установка значений по умолчанию для тестов

Revision ID: c8d9886333e9
Revises: 41c93378bbd7
Create Date: 2024-02-27 21:03:39.015514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d9886333e9'
down_revision: Union[str, None] = '41c93378bbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
